### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Tianyi6679**

### CODE REVIEW

**Comment by Tianyi6679** [comment]
Hi, Jared
I totally understand your concern. But maybe you mistook my intent to implement this class.
Eventbuilder is actually an accessory class that helps us build our event class easily. Not for users. The constructor of schedule event takes 4 parameters. However, with the help of eventbuilder, we can create event with fewer parameters and in a more visually appealing way as shown in my examples. Its a tool but not a core component of our project. So, feel free to use it.

Tianyi Ma

**Comment by jleeong** [comment]
I see what you were trying to do. I'm just saying that we can make ScheduleEvent objects just as easily already:
`new ScheduleEvent(Dependencies1, 200, 300, "Midterm is so hard")`

I feel like this syntax is easier to understand and more efficient. It'll reduce confusion for all the other group members if we just keep it simple.

**Comment by Tianyi6679** [comment]
Ohh, I see. Simplicity and efficiency are absolutely critical for us. I am
worrying that if some events do not have any dependencies, then this
constructor wont work. Maybe writing another constructor for such situation?

**Comment by jleeong** [comment]
yea we can overload the constructor.
`public ScheduleEvent(TimeBlock start, TimeBlock end, String desc)`
should work fine.

**Pull request merged**
